"""Narrow local typing for the graphviz 0.21 Source API used here."""

class ExecutableNotFound(RuntimeError): ...
class CalledProcessError(RuntimeError): ...

class Source:
    source: str
    def __init__(self, source: str) -> None: ...
    def pipe(self, format: str | None = None) -> bytes: ...
